// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9HlpWrr5Fexp40stfTpNf1OMrzapOY54',
    appId: '1:780223963970:web:4f233e58660846ef5b5edb',
    messagingSenderId: '780223963970',
    projectId: 'clinica-ulagos-app',
    authDomain: 'clinica-ulagos-app.firebaseapp.com',
    storageBucket: 'clinica-ulagos-app.appspot.com',
    measurementId: 'G-MTZMH8LTE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKRVVG2Ujw_COx8rcKSAnuNB070-3QGg',
    appId: '1:780223963970:android:4bd238ec36f5a4815b5edb',
    messagingSenderId: '780223963970',
    projectId: 'clinica-ulagos-app',
    storageBucket: 'clinica-ulagos-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmvGoou10HFqdZYw10fnI66tGL5xH_NPg',
    appId: '1:780223963970:ios:39fd201df360c79a5b5edb',
    messagingSenderId: '780223963970',
    projectId: 'clinica-ulagos-app',
    storageBucket: 'clinica-ulagos-app.appspot.com',
    iosBundleId: 'com.example.clinicaUlagosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmvGoou10HFqdZYw10fnI66tGL5xH_NPg',
    appId: '1:780223963970:ios:1c36ec173147d7505b5edb',
    messagingSenderId: '780223963970',
    projectId: 'clinica-ulagos-app',
    storageBucket: 'clinica-ulagos-app.appspot.com',
    iosBundleId: 'com.example.clinicaUlagosApp.RunnerTests',
  );
}
